package message;

public enum MessageType {

    SOURCE_LINE,
    SYNTAX_ERROR,
    PARSER_SUMMARY, INTERPRETER_SUMMARY, COMPILER_SUMMARY,
    MISCELLANEOUS, TOKEN,
    ASSIGN, FETCH, BREAKPOINT, RETURN_ERROR,
    CALL, RETURN,
}
